### PR TITLE
Bugfix stride

### PR DESCRIPTION
**Pull request by npinto**

### CODE REVIEW

**Comment by npinto** [comment]
bump

**Comment by poilvert** [comment]
changed the codes so as to check for proper shape in core operations. As soon as the tests from PR #4 will be merged I will add tests to elicit these.

**Comment by npinto** [comment]
TODO:
- test that explicitly expose the previous bug
- quick smoke tests

**Comment by poilvert** [comment]
adressed all of the issues.

**Comment by npinto** [comment]
Looks good. Could you rebase / merge from master so that we can merge this cleanly?

**Comment by poilvert** [comment]
I rebased from the NSF master. It replayed the history. I hope I did not do something wrong!

**Comment by npinto** [comment]
Still can't merge. Will do it the other way.

**Comment by npinto** [comment]
@poilvert, can we get _just_ the stride thing with tests in a separate PR ?

**Comment by npinto** [comment]
bump (it would be nice to merge the latest PRs so that we don't forget about them)

**Comment by poilvert** [comment]
just made a new PR.

On Tue, Apr 10, 2012 at 11:18 PM, Nicolas Pinto <
reply@reply.github.com

> wrote:
> 
> bump (it would be nice to merge the latest PRs so that we don't forget
> about them)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nsf-ri-ubicv/sthor/pull/3#issuecomment-5061381

## 

Nicolas POILVERT, PhD
Post-doctoral Fellow
Rowland Institute at Harvard

**Pull request closed without merging**
